# Copyright (C) 2026 NV Access Limited, Abdel
# This file is covered by the GNU General Public License.
# See the file COPYING for more details.

"""General string, formatting, and structural data helpers."""

from collections.abc import MutableSequence
import re
from typing import Any

import tomlkit


def formatAuthorList(rawAuthorsText: str) -> tomlkit.items.Array:
	"""Convert a comma-separated string of authors into a tomlkit multiline array.

	Omits empty 'email' fields to prevent validation errors during 'uv run scons'
	and PEP 621 metadata compliance checks.

	:param rawAuthorsText: The raw authors string (e.g., "Author Name <email@example.com>, Another").
	:return: A tomlkit.items.Array object containing inline tables.
	"""
	authorsArray: tomlkit.items.Array = tomlkit.array()
	authorsArray.multiline(True)

	authorParts: list[str] = [p.strip() for p in rawAuthorsText.split(",") if p.strip()]

	partItem: str
	for partItem in authorParts:
		regexMatch: re.Match[str] | None = re.match(r"^(.*?)\s*<(.*?)>$", partItem)
		if regexMatch:
			authorName: str = regexMatch.group(1).strip()
			authorEmail: str = regexMatch.group(2).strip()
			authorInlineTable: tomlkit.items.InlineTable = tomlkit.inline_table()
			authorDataDict: dict[str, str] = {"name": authorName}
			if authorEmail:
				authorDataDict["email"] = authorEmail
			authorInlineTable.update(authorDataDict)
			authorsArray.append(authorInlineTable)
		elif partItem:
			authorInlineTable = tomlkit.inline_table()
			authorInlineTable.update({"name": partItem})
			authorsArray.append(authorInlineTable)

	return authorsArray


def fixTomlIndentation(tomlContentText: str) -> str:
	"""Post-process serialized TOML string to enforce tab-based indentation.

	Converts space-based leading indents into hard tabs while preserving the exact
	structural layout and line breaks produced by tomlkit.

	:param tomlContentText: The raw TOML string generated by tomlkit.dumps().
	:return: The TOML string with strictly enforced tab indentation.
	"""
	contentLines: list[str] = tomlContentText.splitlines(keepends=True)
	fixedLines: list[str] = []

	lineItem: str
	for lineItem in contentLines:
		if lineItem.startswith("    "):
			lineItem = re.sub(r"^(?: {4})+", lambda matchObj: "\t" * (len(matchObj.group(0)) // 4), lineItem)
		fixedLines.append(lineItem)

	outputText: str = "".join(fixedLines)
	outputText = re.sub(r"\n{3,}", "\n\n", outputText)
	if not outputText.endswith("\n"):
		outputText += "\n"
	return outputText


def cleanupPlaceholderAuthors(projectSectionDict: dict[str, Any]) -> None:
	"""Remove NV Access placeholder entries from authors and maintainers fields in-place.

	:param projectSectionDict: The project table/dictionary within the TOML structure.
	:return: None
	"""
	fieldName: str
	for fieldName in ["authors", "maintainers"]:
		if fieldName in projectSectionDict and isinstance(projectSectionDict[fieldName], (list, MutableSequence)):
			authorList: Any = projectSectionDict[fieldName]
			listIndex: int
			for listIndex in range(len(authorList) - 1, -1, -1):
				authorItem: Any = authorList[listIndex]
				authorName: Any = authorItem.get("name", "") if hasattr(authorItem, "get") else ""
				if not authorName and isinstance(authorItem, dict):
					authorName = authorItem.get("name", "")

				if str(authorName).strip().lower() in ["nv access", "nvaccess"]:
					authorList.pop(listIndex)


def getBasePackageName(dependencyStringText: str) -> str:
	"""Extract base package name robustly (handles !=, <=, ~=, @ URLs, markers, etc.).

	:param dependencyStringText: The raw dependency string.
	:return: The normalized base package name in lowercase.
	"""
	regexMatch: re.Match[str] | None = re.match(r"^[A-Za-z0-9][A-Za-z0-9._-]*", dependencyStringText.strip())
	basePackageName: str = regexMatch.group(0) if regexMatch else dependencyStringText.strip()
	return basePackageName.lower().replace("_", "-")


def insertKeyAfter(table: Any, targetKey: str, newKey: str, value: Any) -> None:
	"""Insert or move a key in a TOML table immediately after a target key.

	:param table: The target TOML table or dictionary to modify.
	:param targetKey: The key after which the new key will be inserted.
	:param newKey: The key name to insert or reposition.
	:param value: The value associated with the new key.
	:return: None
	"""
	tableItems: list[tuple[Any, Any]] = list(table.items())
	table.clear()

	isInserted: bool = False
	keyItem: Any
	valueItem: Any
	for keyItem, valueItem in tableItems:
		if keyItem == newKey:
			continue

		table[keyItem] = valueItem

		if keyItem == targetKey:
			table[newKey] = value
			isInserted = True

	if not isInserted:
		table[newKey] = value
