# Copyright (C) 2026 NV Access Limited, Abdel
# This file is covered by the GNU General Public License.
# See the file COPYING for more details.

from collections.abc import MutableMapping, MutableSequence
import argparse
import ast
import logging
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any, cast

import tomlkit

logger = logging.getLogger("syncAddon")


def buildArgParser() -> argparse.ArgumentParser:
	"""Build and configure the command-line argument parser.

	:return: Configured ArgumentParser object.
	"""
	parser = argparse.ArgumentParser(
		description="Non-destructive industrial update tool for NVDA Add-ons.",
	)
	parser.add_argument(
		"-ad", "--addon-dir",
		dest="addonDir",
		default=None,
		help="Path to the root directory of the add-on to update (defaults to current directory).",
	)
	parser.add_argument(
		"-td", "--template-dir",
		dest="templateDir",
		default=None,
		help="Path to a local directory containing the NVDA AddonTemplate to use instead of fetching it via Git.",
	)
	parser.add_argument(
		"-dr", "--dry-run",
		dest="dryRun",
		action="store_true",
		help="Simulate execution without modifying any files.",
	)
	parser.add_argument(
		"-s", "--skip-backup",
		dest="skipBackup",
		action="store_true",
		help="Disable safety automatic project backup.",
	)
	return parser


def parseAstDict(node: ast.Dict) -> dict[str, Any]:
	"""Extract key-value pairs from an AST Dict node.

	:param node: The ast.Dict node to parse.
	:return: A dictionary containing the extracted keys and values.
	"""
	extracted: dict[str, Any] = {}
	for keyNode, valNode in zip(node.keys, node.values):
		if keyNode is None:
			continue
		key = getattr(keyNode, "value", None)
		if isinstance(valNode, ast.Call) and getattr(valNode.func, "id", None) == "_":
			valNode = valNode.args[0]
		val = getattr(valNode, "value", None)
		if key is not None:
			extracted[key] = val
	return extracted


def parseAstKeywords(keywords: list[ast.keyword]) -> dict[str, Any]:
	"""Extract key-value pairs from a list of AST keyword nodes.

	:param keywords: The list of ast.keyword nodes to parse.
	:return: A dictionary containing the extracted keys and values.
	"""
	extracted: dict[str, Any] = {}
	for keyword in keywords:
		key = keyword.arg
		valNode = keyword.value
		if isinstance(valNode, ast.Call) and getattr(valNode.func, "id", None) == "_":
			valNode = valNode.args[0]
		val = getattr(valNode, "value", None)
		if key is not None:
			extracted[key] = val
	return extracted


def usesOsModule(node: ast.AST) -> bool:
	"""Check recursively if an AST node contains an actual reference to the 'os' module.

	:param node: The AST node to inspect.
	:return: True if the node references 'os', False otherwise.
	"""
	for child in ast.walk(node):
		if isinstance(child, ast.Name) and child.id == "os":
			return True
	return False


def formatAuthorList(rawAuthors: str) -> tomlkit.items.Array:
	"""Convert a comma-separated string of authors into a tomlkit multiline array.

	:param rawAuthors: The raw authors string (e.g., "Author Name <email@example.com>, Another").
	:return: A tomlkit.items.Array object containing inline tables.
	"""
	authorsList = tomlkit.array()
	authorsList.multiline(True)

	parts = [p.strip() for p in rawAuthors.split(",") if p.strip()]

	for part in parts:
		m = re.match(r"^(.*?)\s*<(.*?)>$", part)
		if m:
			t = tomlkit.inline_table()
			t.update({"name": m.group(1).strip(), "email": m.group(2).strip()})
			authorsList.append(t)
		elif part:
			t = tomlkit.inline_table()
			t.update({"name": part, "email": ""})
			authorsList.append(t)

	return authorsList


def fixTomlIndentation(tomlText: str) -> str:
	"""Replace leading 4-space indentations with a tab inside maintainers/authors array blocks.

	:param tomlText: The raw TOML string generated by tomlkit.
	:return: The TOML string with strictly enforced tab indentation.
	"""
	lines = tomlText.splitlines(keepends=True)
	fixedLines = []
	inTargetArray = False

	for line in lines:
		stripped = line.strip()
		if re.match(r"^(?:maintainers|authors)\s*=\s*\[", stripped):
			inTargetArray = True
			fixedLines.append(line)
			continue

		if inTargetArray:
			if stripped == "]":
				inTargetArray = False
				fixedLines.append(line)
			else:
				fixedLines.append(re.sub(r"^ {4}", "\t", line))
		else:
			fixedLines.append(line)

	return "".join(fixedLines)


def createPyprojectFromTemplate(templatePath: Path, metadata: dict[str, Any]) -> tomlkit.TOMLDocument:
	"""Create a new pyproject.toml document based on the official template, preserving tab indentation.

	:param templatePath: Path to the reference template pyproject.toml file.
	:param metadata: Extracted metadata dictionary from legacy buildVars/manifest.
	:return: A tomlkit TOMLDocument adhering to template tab formatting and populated with metadata.
	"""
	with templatePath.open("r", encoding="utf-8") as f:
		doc = tomlkit.parse(f.read())

	if "project" not in doc:
		doc["project"] = tomlkit.table()

	projectSection = doc["project"]

	if "addon_name" in metadata and metadata["addon_name"]:
		projectSection["name"] = metadata["addon_name"]

	if "addon_summary" in metadata and metadata["addon_summary"]:
		projectSection["description"] = metadata["addon_summary"]

	addonUrl = str(metadata.get("addon_url", "")).strip()
	if addonUrl:
		if "urls" not in projectSection:
			projectSection["urls"] = tomlkit.table()
		projectSection["urls"]["Repository"] = addonUrl

	if "addon_author" in metadata and metadata["addon_author"]:
		projectSection["maintainers"] = formatAuthorList(metadata["addon_author"])

	return doc


def cleanupPlaceholderAuthors(projectSection: dict[str, Any]) -> None:
	"""Remove NV Access placeholder entries from authors and maintainers fields in-place.

	:param projectSection: The project table/dictionary within the TOML structure.
	:return: None
	"""
	for field in ["authors", "maintainers"]:
		if field in projectSection and isinstance(projectSection[field], (list, MutableSequence)):
			tomlList = projectSection[field]
			for i in range(len(tomlList) - 1, -1, -1):
				item = tomlList[i]
				name = item.get("name", "") if hasattr(item, "get") else ""
				if not name and isinstance(item, dict):
					name = item.get("name", "")

				if str(name).strip().lower() in ["nv access", "nvaccess"]:
					tomlList.pop(i)


def getBasePackageName(s: str) -> str:
	"""Extract base package name robustly (handles !=, <=, ~=, @ URLs, markers, etc.).

	:param s: The raw dependency string.
	:return: The normalized base package name in lowercase.
	"""
	m = re.match(r"^[A-Za-z0-9][A-Za-z0-9._-]*", s.strip())
	return m.group(0).lower() if m else s.strip().lower()


def replaceAstRange(tplLines: list[str], replacements: dict[tuple[int, int], str]) -> None:
	"""Apply AST line replacements on a line-by-line list in reverse order.

	:param tplLines: The list of lines representing the file content.
	:param replacements: A dictionary mapping (start_line, end_line) tuples to the replacing string.
	:return: None
	"""
	sortedRanges = sorted(replacements.keys(), key=lambda x: x[0], reverse=True)
	for start, end in sortedRanges:
		tplLines[start:end] = [replacements[(start, end)]]


def deepMergeDicts(dictProj: dict[str, Any], dictTpl: dict[str, Any]) -> dict[str, Any]:
	"""Recursively merges dictTpl into dictProj.

	:param dictProj: The original dictionary to be updated.
	:param dictTpl: The template dictionary whose values will be merged into dictProj.
	:return: The updated dictProj with merged values from dictTpl.
	"""
	for key, value in dictTpl.items():
		if key in dictProj:
			projVal = dictProj[key]
			if isinstance(projVal, MutableMapping) and isinstance(value, MutableMapping):
				deepMergeDicts(projVal, value)
			elif isinstance(projVal, MutableSequence) and isinstance(value, MutableSequence):
				for item in value:
					if item not in projVal:
						projVal.append(item)
			else:
				pass
		else:
			dictProj[key] = value
	return dictProj


def extractBuildvarsMetadata(filePath: str | Path) -> tuple[dict[str, Any], dict[str, tuple[ast.AST, str]]]:
	"""Extract metadata and raw assignment expressions along with AST nodes from buildVars.py safely.

	:param filePath: The path to the buildVars.py file.
	:return: A tuple containing two dictionaries: metadata and globalVars mapping var_name -> (ast_node, unparsed_expr).
	"""
	p = Path(filePath)
	if not p.exists():
		return {}, {}

	with p.open("r", encoding="utf-8") as f:
		try:
			tree = ast.parse(f.read())
		except SyntaxError as e:
			logger.error("Syntax error while reading %s: %s", p, e)
			return {}, {}

	metadata: dict[str, Any] = {}
	globalVars: dict[str, tuple[ast.AST, str]] = {}
	topLevelVars: set[str] = {
		"pythonSources",
		"excludedFiles",
		"baseLanguage",
		"markdownExtensions",
		"brailleTables",
		"symbolDictionaries",
		"speechDictionaries",
	}

	for node in ast.walk(tree):
		if isinstance(node, ast.Assign) and len(node.targets) == 1:
			target = node.targets[0]
			if not isinstance(target, ast.Name):
				continue
			varName = target.id

			if varName == "addon_info":
				if isinstance(node.value, ast.Dict):
					metadata.update(parseAstDict(node.value))
				elif isinstance(node.value, ast.Call) and getattr(node.value.func, "id", None) == "AddonInfo":
					metadata.update(parseAstKeywords(node.value.keywords))
			elif varName in topLevelVars:
				globalVars[varName] = (node.value, ast.unparse(node.value))
		elif isinstance(node, ast.AnnAssign):
			if isinstance(node.target, ast.Name) and node.target.id in topLevelVars:
				if node.value is not None:
					globalVars[node.target.id] = (node.value, ast.unparse(node.value))

	return metadata, globalVars


def mergePyprojectToml(projPath: str | Path, tplPath: str | Path, metadata: dict[str, Any], dryRun: bool = False) -> str:
	"""Merge template pyproject.toml configuration into the developer's file.

	:param projPath: Path to the existing pyproject.toml file.
	:param tplPath: Path to the template pyproject.toml file.
	:param metadata: Dictionary containing legacy metadata values from buildVars.py.
	:param dryRun: If True, simulate the merge without writing changes to disk.
	:return: A string indicating the result of the merge operation.
	"""
	pTpl = Path(tplPath)
	pProj = Path(projPath)

	if not pTpl.exists():
		return "skipped (no template found)"

	if not pProj.exists():
		try:
			projData = createPyprojectFromTemplate(pTpl, metadata)
			if not dryRun:
				tomlOutput = fixTomlIndentation(tomlkit.dumps(projData))
				pProj.parent.mkdir(parents=True, exist_ok=True)
				with pProj.open("w", encoding="utf-8") as f:
					f.write(tomlOutput)
				logger.info("Created missing pyproject.toml at %s", pProj)
			return "created from template"
		except Exception as e:
			logger.error("Failed to create pyproject.toml: %s", e)
			return f"failed to create from template ({str(e)})"

	try:
		with pProj.open("r", encoding="utf-8") as f:
			projData = tomlkit.parse(f.read())
		with pTpl.open("r", encoding="utf-8") as f:
			tplData = tomlkit.parse(f.read())

		wasOriginallyNvaccess = False
		if "project" in projData:
			for field in ["authors", "maintainers"]:
				if field in projData["project"] and isinstance(projData["project"][field], (list, MutableSequence)):
					for item in projData["project"][field]:
						name = item.get("name", "") if hasattr(item, "get") else ""
						if not name and isinstance(item, dict):
							name = item.get("name", "")
						if str(name).strip().lower() in ["nv access", "nvaccess"]:
							wasOriginallyNvaccess = True
							break

		projDeps = []
		if "project" in projData and "dependencies" in projData["project"]:
			projDeps = list(projData["project"]["dependencies"])
			del projData["project"]["dependencies"]

		mergedData = deepMergeDicts(cast(dict[str, Any], projData), cast(dict[str, Any], tplData))

		if "project" in mergedData:
			projectSection = mergedData["project"]

			if not wasOriginallyNvaccess:
				cleanupPlaceholderAuthors(projectSection)

			if "dependencies" in projectSection:
				tplDeps = projectSection["dependencies"]
				tplBases = {getBasePackageName(d) for d in tplDeps}

				# Collect all tooling package names managed by template dependency groups
				groupBases: set[str] = set()
				if "dependency-groups" in mergedData:
					for grp in mergedData["dependency-groups"].values():
						if isinstance(grp, list):
							for item in grp:
								if isinstance(item, str):
									groupBases.add(getBasePackageName(item))

				for dep in projDeps:
					base = getBasePackageName(dep)
					# Only append to project.dependencies if not already present in template
					# dependencies nor managed by PEP 735 dependency groups
					if base not in tplBases and base not in groupBases:
						tplDeps.append(dep)

		if not dryRun:
			tomlOutput = fixTomlIndentation(tomlkit.dumps(cast(tomlkit.TOMLDocument, mergedData)))
			with pProj.open("w", encoding="utf-8") as f:
				f.write(tomlOutput)
		return "merged intelligently (tomlkit)"
	except Exception as e:
		logger.error("Failed to merge pyproject.toml: %s", e)
		return f"failed to merge ({str(e)})"


def mergeBuildvarsFile(
	projPath: str | Path,
	tplPath: str | Path,
	metadata: dict[str, Any],
	globalVars: dict[str, tuple[ast.AST, str]],
	dryRun: bool = False,
) -> str:
	"""Merge template buildVars.py using precise AST range tracking to prevent multiline leaks.

	:param projPath: Path to the existing buildVars.py file.
	:param tplPath: Path to the template buildVars.py file.
	:param metadata: Dictionary containing metadata values to update.
	:param globalVars: Dictionary containing global variables mapping var_name -> (ast_node, unparsed_expr).
	:param dryRun: If True, simulate the merge without writing changes to disk.
	:return: A string indicating the result of the merge operation.
	"""
	pTpl = Path(tplPath)
	pProj = Path(projPath)

	if not pTpl.exists():
		return "failed (no template found)"

	with pTpl.open("r", encoding="utf-8") as f:
		tplContent = f.read()

	try:
		tree = ast.parse(tplContent)
	except SyntaxError as e:
		return f"failed (template syntax error: {e})"

	tplLines = tplContent.splitlines(keepends=True)
	replacements: dict[tuple[int, int], str] = {}
	requiresOsImport = False

	for node in ast.walk(tree):
		if isinstance(node, ast.Call) and getattr(node.func, "id", None) == "AddonInfo":
			for kw in node.keywords:
				if kw.arg in metadata:
					key = kw.arg
					val = metadata[key]
					if val is None:
						formattedVal = "None"
					elif isinstance(val, str):
						isTranslatable = key in ["addon_summary", "addon_description", "addon_changelog"]
						formattedVal = f"_({val!r})" if isTranslatable else repr(val)
					else:
						formattedVal = str(val)

					if kw.end_lineno is not None:
						lineContent = tplLines[kw.lineno - 1]
						indent = lineContent[: len(lineContent) - len(lineContent.lstrip())]
						replacements[(kw.lineno - 1, kw.end_lineno)] = f"{indent}{key}={formattedVal},\n"

		elif isinstance(node, ast.Assign) and len(node.targets) == 1:
			target = node.targets[0]
			if isinstance(target, ast.Name) and target.id in globalVars:
				key = target.id
				valNode, valExpression = globalVars[key]
				if usesOsModule(valNode):
					requiresOsImport = True
				if node.end_lineno is not None:
					lineContent = tplLines[node.lineno - 1]
					indent = lineContent[: len(lineContent) - len(lineContent.lstrip())]
					replacements[(node.lineno - 1, node.end_lineno)] = (
						f"{indent}{key} = {valExpression}\n"
					)

		elif isinstance(node, ast.AnnAssign):
			if isinstance(node.target, ast.Name) and node.target.id in globalVars:
				key = node.target.id
				valNode, valExpression = globalVars[key]
				if usesOsModule(valNode):
					requiresOsImport = True
				if node.end_lineno is not None:
					lineContent = tplLines[node.lineno - 1]
					indent = lineContent[: len(lineContent) - len(lineContent.lstrip())]
					typeStr = ast.unparse(node.annotation)
					replacements[(node.lineno - 1, node.end_lineno)] = (
						f"{indent}{key}: {typeStr} = {valExpression}\n"
					)

	replaceAstRange(tplLines, replacements)

	if requiresOsImport:
		hasOsImport = any("import os" in line for line in tplLines[:15])
		if not hasOsImport:
			tplLines.insert(0, "import os\n")

	if not dryRun:
		with pProj.open("w", encoding="utf-8") as f:
			f.writelines(tplLines)
	return "merged & structured (AST verified)"


def runSynchronization(tempDir: str, addonDir: str, dryRun: bool) -> None:
	"""Synchronizes template machinery files from the temporary workspace into the target directory.

	:param tempDir: Path to the local temporary directory containing the template files.
	:param addonDir: Path to the target add-on root directory.
	:param dryRun: If True, simulate the sync without writing changes to disk.
	:return: None
	"""
	logger.info("Synchronizing template machinery files...")
	protectedElements = {
		"readme.md",
		"changelog.md",
		"addon",
		".git",
		"__pycache__",
		".venv",
		"docs",
		".ruff_cache",
		"tests",
	}

	ignoreFilePath = os.path.join(addonDir, ".addonmergeignore")
	if os.path.exists(ignoreFilePath):
		logger.info("Reading local custom exclusions from .addonmergeignore...")
		try:
			with open(ignoreFilePath, "r", encoding="utf-8") as f:
				for line in f:
					cleanLine = line.strip().lower()
					if cleanLine and not cleanLine.startswith("#"):
						protectedElements.add(cleanLine)
		except Exception as e:
			logger.warning("Failed to parse .addonmergeignore (%s)", e)

	syncReport: list[str] = []

	for item in os.listdir(tempDir):
		if item.lower() in protectedElements:
			syncReport.append(f"- **{item}**: skipped (protected scope)")
			continue

		if item in ["buildVars.py", "pyproject.toml"]:
			continue

		srcItem = os.path.join(tempDir, item)
		dstItem = os.path.join(addonDir, item)

		try:
			if os.path.isdir(srcItem):
				if not dryRun:
					os.makedirs(dstItem, exist_ok=True)
					shutil.copytree(srcItem, dstItem, dirs_exist_ok=True)
				syncReport.append(f"- **{item}/**: merged safely")
			else:
				if not dryRun:
					shutil.copy2(srcItem, dstItem)
				syncReport.append(f"- **{item}**: synchronized")
		except Exception as e:
			syncReport.append(f"- **{item}**: failed ({str(e)})")

	logger.info("Processing structural configuration merges...")
	templateBuildvars = os.path.join(tempDir, "buildVars.py")
	templatePyproject = os.path.join(tempDir, "pyproject.toml")

	oldBuildvars = os.path.join(addonDir, "buildVars.py")
	oldPyproject = os.path.join(addonDir, "pyproject.toml")

	bvMeta, bvGlobals = extractBuildvarsMetadata(oldBuildvars)
	addonName = bvMeta.get("addon_name", os.path.basename(addonDir))

	bvStatus = mergeBuildvarsFile(oldBuildvars, templateBuildvars, bvMeta, bvGlobals, dryRun)
	ppStatus = mergePyprojectToml(oldPyproject, templatePyproject, bvMeta, dryRun)

	logger.info("=" * 50)
	logger.info("UPDATE REPORT")
	logger.info("=" * 50)
	logger.info("Add-on: %s", addonName)
	logger.info("\nTemplate synchronization:")
	for entry in syncReport:
		logger.info("  %s", entry)
	logger.info(
		"\nConfiguration files:\n  - **buildVars.py**: %s\n  - **pyproject.toml**: %s",
		bvStatus,
		ppStatus,
	)


def main() -> None:
	"""Execute main CLI entry point for the NVDA Add-on update tool."""
	logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")

	parser = buildArgParser()
	args = parser.parse_args()

	addonDirInput = args.addonDir
	if addonDirInput:
		addonDir = os.path.abspath(addonDirInput)
	else:
		cwd = Path(os.getcwd()).resolve()
		addonRoot = next((p for p in (cwd, *cwd.parents) if (p / "buildVars.py").exists()), None)
		addonDir = str(addonRoot) if addonRoot is not None else str(cwd)

	logger.info("=== NVDA ADD-ON UPDATE TOOL ===")
	logger.info("Target Directory: %s", addonDir)

	oldBuildvars = os.path.join(addonDir, "buildVars.py")

	if not os.path.exists(oldBuildvars):
		logger.error("'%s' does not appear to be a valid NVDA Add-on (missing buildVars.py).", addonDir)
		if sys.stdin.isatty():
			input("\nPress Enter to exit...")
		sys.exit(1)

	logger.info("Phase 1: Analyzing existing project structure and metadata...")
	bvMeta, _ = extractBuildvarsMetadata(oldBuildvars)
	addonName = bvMeta.get("addon_name", os.path.basename(addonDir))
	logger.info("Target Add-on Identified: %s", addonName)

	if args.dryRun:
		logger.info("RUNNING IN SIMULATION MODE (--dry-run). No files will be modified.")

	logger.info("Phase 2: Safety backup verification...")
	if args.dryRun:
		logger.info("Safety backup skipped (simulation mode active).")
	elif args.skipBackup:
		logger.info("Safety backup skipped (--skip-backup requested by user).")
	else:
		backupDir = f"{addonDir}_bak_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
		logger.info("Creating safety automatic backup in: %s...", os.path.basename(backupDir))
		try:
			shutil.copytree(
				addonDir,
				backupDir,
				ignore=shutil.ignore_patterns(".git", "__pycache__", ".venv", "*_bak_*"),
			)
			logger.info("Backup created successfully.")
		except Exception as e:
			logger.error("Critical: Backup failed (%s). Aborting update.", e)
			if sys.stdin.isatty():
				input("\nPress Enter to exit...")
			sys.exit(1)

	if args.templateDir:
		templatePath = os.path.abspath(args.templateDir)
		logger.info("Phase 3: Using local template directory: %s", templatePath)
		if not os.path.exists(os.path.join(templatePath, "buildVars.py")):
			logger.error("Provided template directory does not appear to be a valid NVDA AddonTemplate (missing buildVars.py).")
			if sys.stdin.isatty():
				input("\nPress Enter to exit...")
			sys.exit(1)
		runSynchronization(templatePath, addonDir, args.dryRun)
	else:
		logger.info("Phase 3: Provisioning latest official NVDA AddonTemplate via Git...")
		with tempfile.TemporaryDirectory() as tempDir:
			logger.info("Cloning template into temporary workspace...")
			templateUrl = "https://github.com/nvaccess/AddonTemplate.git"

			try:
				subprocess.run(
					["git", "clone", "--depth", "1", templateUrl, tempDir],
					check=True,
					stdout=subprocess.DEVNULL,
					stderr=subprocess.PIPE,
				)
				logger.info("Template cloned successfully.")
			except (subprocess.CalledProcessError, FileNotFoundError) as e:
				logger.error("Failed to execute git clone. Make sure Git is available in your PATH.")
				if isinstance(e, subprocess.CalledProcessError) and e.stderr:
					logger.error("Details: %s", e.stderr.decode("utf-8", errors="ignore"))
				if sys.stdin.isatty():
					input("\nPress Enter to exit...")
				sys.exit(1)

			runSynchronization(tempDir, addonDir, args.dryRun)

	if not args.dryRun:
		logger.info("Project successfully updated. Workspace cleared.")
	else:
		logger.info("Simulation finished. Workspace cleared.")


if __name__ == "__main__":
	main()
